const fs = require('fs');
const parts = [];

parts.push('"use client"');
parts.push('');
parts.push("import { useState, useEffect } from 'react'");
parts.push("import { useSearchParams, useRouter, usePathname } from 'next/navigation'");
parts.push("import Link from 'next/link'");
parts.push("import Image from 'next/image'");
parts.push("import { ProductCard } from '@/components/products'");
parts.push("import { productsApi } from '@/lib/endpoints-shop'");
parts.push("import { Button } from '@/components/ui/Button'");
parts.push("import { Select } from '@/components/ui/Select'");
parts.push("import { Input } from '@/components/ui/Input'");
parts.push('');
parts.push('const SORT_OPTIONS = [');
parts.push('  { value: "createdAt", label: "Newest" },');
parts.push('  { value: "name", label: "Name A-Z" },');
parts.push('  { value: "-name", label: "Name Z-A" },');
parts.push('  { value: "price", label: "Price Low to High" },');
parts.push('  { value: "-price", label: "Price High to Low" },');
parts.push('  { value: "-averageRating", label: "Top Rated" },');
parts.push('];');
parts.push('');
parts.push('const LIMIT_OPTIONS = [');
parts.push('  { value: "12", label: "12 per page" },');
parts.push('  { value: "24", label: "24 per page" },');
parts.push('  { value: "48", label: "48 per page" },');
parts.push('];');
parts.push('');
parts.push('export default function ProductsPage() {');
parts.push('  const searchParams = useSearchParams();');
parts.push('  const router = useRouter();');
parts.push('  const pathname = usePathname();');
parts.push('  ');
parts.push('  const [products, setProducts] = useState<any[]>([]);');
parts.push('  const [categories, setCategories] = useState<string[]>([]);');
parts.push('  const [loading, setLoading] = useState(true);');
parts.push('  const [total, setTotal] = useState(0);');
parts.push('  const [totalPages, setTotalPages] = useState(0);');
parts.push('');
parts.push("  const page = parseInt(searchParams.get('page') || '1');");
parts.push("  const limit = parseInt(searchParams.get('limit') || '12');");
parts.push("  const sort = searchParams.get('sort') || 'createdAt';");
parts.push("  const order = searchParams.get('order') || 'DESC';");
parts.push("  const category = searchParams.get('category') || '';");
parts.push("  const search = searchParams.get('search') || '';");
parts.push("  const minPrice = searchParams.get('minPrice') || '';");
parts.push("  const maxPrice = searchParams.get('maxPrice') || '';");
parts.push('');
parts.push('  const fetchProducts = async () => {');
parts.push('    setLoading(true);');
parts.push('    try {');
parts.push('      const params = { page, limit, sort, order };');
parts.push('      if (category) params.category = category;');
parts.push('      if (search) params.search = search;');
parts.push('      if (minPrice) params.minPrice = parseFloat(minPrice);');
parts.push('      if (maxPrice) params.maxPrice = parseFloat(maxPrice);');
parts.push('');
parts.push('      const response = await productsApi.getProducts(params);');
parts.push('      setProducts(response.data.data?.data || []);');
parts.push('      setTotal(response.data.data?.total || 0);');
parts.push('      setTotalPages(response.data.data?.totalPages || 0);');
parts.push('    } catch (error) {');
parts.push('      console.error("Failed to fetch products:", error);');
parts.push('    } finally {');
parts.push('      setLoading(false);');
parts.push('    }');
parts.push('  };');
parts.push('');
parts.push('  const fetchCategories = async () => {');
parts.push('    try {');
parts.push('      const response = await productsApi.getProducts({ limit: 100 });');
parts.push('      const products = response.data.data?.data || [];');
parts.push('      const cats = [...new Set(products.map((p) => p.category?.name).filter(Boolean))];');
parts.push('      setCategories(cats);');
parts.push('    } catch (error) {');
parts.push('      console.error("Failed to fetch categories:", error);');
parts.push('    }');
parts.push('  };');
parts.push('');
parts.push('  useEffect(() => {');
parts.push('    fetchProducts();');
parts.push('    fetchCategories();');
parts.push('  }, [page, limit, sort, order, category, search, minPrice, maxPrice]);');
parts.push('');
parts.push('  const updateParams = (newParams) => {');
parts.push('    const params = new URLSearchParams(searchParams.toString());');
parts.push('    Object.entries(newParams).forEach(([key, value]) => {');
parts.push('      if (value === null || value === "") {');
parts.push('        params.delete(key);');
parts.push('      } else {');
parts.push('        params.set(key, value);');
parts.push('      }');
parts.push('    });');
parts.push('    params.set("page", "1");');
parts.push('    router.push(${pathname}?);');
parts.push('  };');
parts.push('');
parts.push('  const handleSortChange = (value) => {');
parts.push('    const [field, dir] = value.startsWith("-") ? [value.slice(1), "DESC"] : [value, "ASC"];');
parts.push('    updateParams({ sort: field, order: dir });');
parts.push('  };');
parts.push('');
parts.push('  const handleLimitChange = (value) => {');
parts.push('    updateParams({ limit: value });');
parts.push('  };');
parts.push('');
parts.push('  const handleCategoryChange = (value) => {');
parts.push('    updateParams({ category: value || null });');
parts.push('  };');
parts.push('');
parts.push('  const handleSearch = (e) => {');
parts.push('    e.preventDefault();');
parts.push('    const formData = new FormData(e.currentTarget);');
parts.push('    const searchValue = formData.get("search");');
parts.push('    updateParams({ search: searchValue || null });');
parts.push('  };');
parts.push('');
parts.push('  const handlePriceFilter = () => {');
parts.push('    updateParams({ minPrice: minPrice || null, maxPrice: maxPrice || null });');
parts.push('  };');
parts.push('');
parts.push('  const clearFilters = () => {');
parts.push('    updateParams({ category: null, search: null, minPrice: null, maxPrice: null });');
parts.push('  };');
parts.push('');
parts.push('  const hasActiveFilters = category || search || minPrice || maxPrice;');
parts.push('');
parts.push('  return (');
parts.push('    <div className="min-h-screen bg-secondary-50 dark:bg-secondary-950">');
parts.push('      {/* Page Header */}');
parts.push('      <section className="bg-white dark:bg-secondary-900 border-b border-secondary-200 dark:border-secondary-700">');
parts.push('        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">');
parts.push('          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-6">');
parts.push('            <div>');
parts.push('              <h1 className="text-3xl sm:text-4xl font-display font-bold text-secondary-900 dark:text-white mb-2">');
parts.push('                Shop All Products');
parts.push('              </h1>');
parts.push('              <p className="text-secondary-600 dark:text-secondary-300">');
parts.push('                {total} product{total !== 1 ? "s" : ""} found');
parts.push('              </p>');
parts.push('            </div>');
parts.push('            {hasActiveFilters && (');
parts.push('              <Button variant="ghost" onClick={clearFilters} className="text-sm">');
parts.push('                Clear all filters');
parts.push('              </Button>');
parts.push('            )}');
parts.push('          </div>');
parts.push('        </div>');
parts.push('      </section>');
parts.push('');
parts.push('      {/* Main Content */}');
parts.push('      <section className="py-12">');
parts.push('        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">');
parts.push('          <div className="flex flex-col lg:flex-row gap-8">');
parts.push('            {/* Sidebar Filters */}');
parts.push('            <aside className="lg:w-64 flex-shrink-0">');
parts.push('              <div className="bg-white dark:bg-secondary-900 rounded-xl border border-secondary-200 dark:border-secondary-700 p-6 sticky top-24">');
parts.push('                {/* Search */}');
parts.push('                <form onSubmit={handleSearch} className="mb-6">');
parts.push('                  <label htmlFor="search" className="block text-sm font-medium text-secondary-700 dark:text-secondary-200 mb-2">');
parts.push('                    Search');
parts.push('                  </label>');
parts.push('                  <Input');
parts.push('                    id="search"');
parts.push('                    name="search"');
parts.push('                    placeholder="Search products..."');
parts.push('                    value={search}');
parts.push('                  />');
parts.push('                </form>');
parts.push('');
parts.push('                {/* Categories */}');
parts.push('                {categories.length > 0 && (');
parts.push('                  <div className="mb-6">');
parts.push('                    <label className="block text-sm font-medium text-secondary-700 dark:text-secondary-200 mb-2">');
parts.push('                      Category');
parts.push('                  </label>');
parts.push('                  <Select');
parts.push('                    id="category"');
parts.push('                    value={category}');
parts.push('                    onChange={(e) => handleCategoryChange(e.target.value)}');
parts.push('                    options={[');
parts.push('                        { value: "", label: "All Categories" },');
parts.push('                        ...categories.map(cat => ({ value: cat, label: cat })),');
parts.push('                      ]}');
parts.push('                  />');
parts.push('                  </div>');
parts.push('                )}');
parts.push('');
parts.push('                {/* Price Range */}');
parts.push('                <div className="mb-6">');
parts.push('                  <label className="block text-sm font-medium text-secondary-700 dark:text-secondary-200 mb-2">');
parts.push('                    Price Range');
parts.push('                  </label>');
parts.push('                  <div className="flex items-center gap-2">');
parts.push('                    <Input');
parts.push('                      type="number"');
parts.push('                      placeholder="Min"');
parts.push('                      value={minPrice}');
parts.push('                      onChange={(e) => updateParams({ minPrice: e.target.value || null })}');
parts.push('                      className="w-full"');
parts.push('                    />');
parts.push('                    <span className="text-secondary-400">-</span>');
parts.push('                    <Input');
parts.push('                      type="number"');
parts.push('                      placeholder="Max"');
parts.push('                      value={maxPrice}');
parts.push('                      onChange={(e) => updateParams({ maxPrice: e.target.value || null })}');
parts.push('                      className="w-full"');
parts.push('                    />');
parts.push('                  </div>');
parts.push('                  <Button variant="outline" size="sm" className="w-full mt-2" onClick={handlePriceFilter}>');
parts.push('                    Apply');
parts.push('                  </Button>');
parts.push('                </div>');
parts.push('');
parts.push('                {/* Sort */}');
parts.push('                <div className="mb-6">');
parts.push('                  <label htmlFor="sort" className="block text-sm font-medium text-secondary-700 dark:text-secondary-200 mb-2">');
parts.push('                    Sort By');
parts.push('                  </label>');
parts.push('                  <Select');
parts.push('                    id="sort"');
parts.push('                    value={sort + (order === "DESC" ? "" : "-")}');
parts.push('                    onChange={(e) => handleSortChange(e.target.value)}');
parts.push('                    options={SORT_OPTIONS}');
parts.push('                  />');
parts.push('                </div>');
parts.push('');
parts.push('                {/* Items per page */}');
parts.push('                <div>');
parts.push('                  <label htmlFor="limit" className="block text-sm font-medium text-secondary-700 dark:text-secondary-200 mb-2">');
parts.push('                    Items per page');
parts.push('                  </label>');
parts.push('                  <Select');
parts.push('                    id="limit"');
parts.push('                    value={limit.toString()}');
parts.push('                    onChange={(e) => handleLimitChange(e.target.value)}');
parts.push('                    options={LIMIT_OPTIONS}');
parts.push('                  />');
parts.push('                </div>');
parts.push('              </div>');
parts.push('            </aside>');
parts.push('');
parts.push('            {/* Products Grid */}');
parts.push('            <main className="flex-1 min-w-0">');
parts.push('              {/* Toolbar */}');
parts.push('              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-8">');
parts.push('                <div className="text-secondary-600 dark:text-secondary-300">');
parts.push('                  Showing <span className="font-semibold">{products.length}</span> of <span className="font-semibold">{total}</span> products');
parts.push('                </div>');
parts.push('              </div>');
parts.push('');
parts.push('              {/* Products Grid */}');
parts.push('              {loading ? (');
parts.push('                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">');
parts.push('                  {[...Array(8)].map((_, i) => (');
parts.push('                    <div key={i} className="aspect-[3/4] rounded-xl bg-secondary-100 dark:bg-secondary-800 animate-pulse" />');
parts.push('                  ))}');
parts.push('                </div>');
parts.push('              ) : products.length > 0 ? (');
parts.push('                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6 mb-12">');
parts.push('                  {products.map((product) => (');
parts.push('                    <ProductCard key={product.id} product={product} variant="grid" />');
parts.push('                  ))}');
parts.push('                </div>');
parts.push('              ) : (');
parts.push('                <div className="text-center py-16">');
parts.push('                  <svg className="mx-auto h-12 w-12 text-secondary-300 dark:text-secondary-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">');
parts.push('                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10l-8 4m0-10L4 7v10l8 4" />');
parts.push('                  </svg>');
parts.push('                  <h3 className="mt-4 text-lg font-semibold text-secondary-900 dark:text-white">No products found</h3>');
parts.push('                  <p className="mt-2 text-secondary-500 dark:text-secondary-400">Try adjusting your filters or search terms</p>');
parts.push('                  <Button variant="outline" onClick={clearFilters} className="mt-4">');
parts.push('                    Clear filters');
parts.push('                  </Button>');
parts.push('                </div>');
parts.push('              )}');
parts.push('');
parts.push('              {/* Pagination */}');
parts.push('              {totalPages > 1 && (');
parts.push('                <nav className="flex items-center justify-center gap-2" aria-label="Pagination">');
parts.push('                  <Button');
parts.push('                    variant="outline"');
parts.push('                    size="sm"');
parts.push('                    disabled={page === 1}');
parts.push('                    onClick={() => updateParams({ page: String(page - 1) })}');
parts.push('                  >');
parts.push('                    Previous');
parts.push('                  </Button>');
parts.push('                  <div className="flex items-center gap-1">');
parts.push('                    {Array.from({ length: Math.min(5, totalPages) }, (_, i) => {');
parts.push('                      let pageNum;');
parts.push('                      if (totalPages <= 5) {');
parts.push('                        pageNum = i + 1;');
parts.push('                      } else if (page <= 3) {');
parts.push('                        pageNum = i + 1;');
parts.push('                      } else if (page >= totalPages - 2) {');
parts.push('                        pageNum = totalPages - 4 + i;');
parts.push('                      } else {');
parts.push('                        pageNum = page - 2 + i;');
parts.push('                      }');
parts.push('                      return (');
parts.push('                        <Button');
parts.push('                          key={pageNum}');
parts.push('                          variant={page === pageNum ? "primary" : "outline"}');
parts.push('                          size="sm"');
parts.push('                          onClick={() => updateParams({ page: String(pageNum) })}');
parts.push('                        >');
parts.push('                          {pageNum}');
parts.push('                        </Button>');
parts.push('                      );');
parts.push('                    })}');
parts.push('                  </div>');
parts.push('                  <Button');
parts.push('                    variant="outline"');
parts.push('                    size="sm"');
parts.push('                    disabled={page === totalPages}');
parts.push('                    onClick={() => updateParams({ page: String(page + 1) })}');
parts.push('                  >');
parts.push('                    Next');
parts.push('                  </Button>');
parts.push('                </nav>');
parts.push('              )}');
parts.push('            </main>');
parts.push('          </div>');
parts.push('        </div>');
parts.push('      </section>');
parts.push('    </div>');
parts.push('  );');
parts.push('}');

const fullContent = parts.join("\n");
fs.writeFileSync("F:/westos-platform/apps/frontend/src/app/products/page.tsx", fullContent);
console.log("Products page created successfully");
