const fs = require("fs");
const parts = [];

parts.push("'use client';");
parts.push("");
parts.push("import { useState, useEffect } from 'react';");
parts.push("import { useSearchParams, useRouter, usePathname } from 'next/navigation';");
parts.push("import Link from 'next/link';");
parts.push("import Image from 'next/image';");
parts.push("import { ProductCard } from '@/components/products';");
parts.push("import { productsApi } from '@/lib/endpoints-shop';");
parts.push("import { Button } from '@/components/ui/Button';");
parts.push("import { Select } from '@/components/ui/Select';");
parts.push("import { Input } from '@/components/ui/Input';");
parts.push("");
parts.push("const SORT_OPTIONS = [");
parts.push("  { value: 'createdAt', label: 'Newest' },");
parts.push("  { value: 'name', label: 'Name A-Z' },");
parts.push("  { value: '-name', label: 'Name Z-A' },");
parts.push("  { value: 'price', label: 'Price Low to High' },");
parts.push("  { value: '-price', label: 'Price High to Low' },");
parts.push("  { value: '-averageRating', label: 'Top Rated' },");
parts.push("];");
parts.push("");
parts.push("const LIMIT_OPTIONS = [");
parts.push("  { value: '12', label: '12 per page' },");
parts.push("  { value: '24', label: '24 per page' },");
parts.push("  { value: '48', label: '48 per page' },");
parts.push("];");
parts.push("");
parts.push("export default function ProductsPage() {");
parts.push("  const searchParams = useSearchParams();");
parts.push("  const router = useRouter();");
parts.push("  const pathname = usePathname();");
parts.push("  ");
parts.push("  const [products, setProducts] = useState<any[]>([]);");
parts.push("  const [categories, setCategories] = useState<string[]>([]);");
parts.push("  const [loading, setLoading] = useState(true);");
parts.push("  const [total, setTotal] = useState(0);");
parts.push("  const [totalPages, setTotalPages] = useState(0);");
parts.push("");
parts.push("  const page = parseInt(searchParams.get('page') || '1');");
parts.push("  const limit = parseInt(searchParams.get('limit') || '12');");
parts.push("  const sort = searchParams.get('sort') || 'createdAt';");
parts.push("  const order = searchParams.get('order') || 'DESC';");
parts.push("  const category = searchParams.get('category') || '';");
parts.push("  const search = searchParams.get('search') || '';");
parts.push("  const minPrice = searchParams.get('minPrice') || '';");
parts.push("  const maxPrice = searchParams.get('maxPrice') || '';");
parts.push("");
parts.push("  const fetchProducts = async () => {");
parts.push("    setLoading(true);");
parts.push("    try {");
parts.push("      const params: any = { page, limit, sort, order };");
parts.push("      if (category) params.category = category;");
parts.push("      if (search) params.search = search;");
parts.push("      if (minPrice) params.minPrice = parseFloat(minPrice);");
parts.push("      if (maxPrice) params.maxPrice = parseFloat(maxPrice);");
parts.push("");
parts.push("      const response = await productsApi.getProducts(params);");
parts.push("      setProducts(response.data.data?.data || []);");
parts.push("      setTotal(response.data.data?.total || 0);");
parts.push("      setTotalPages(response.data.data?.totalPages || 0);");
parts.push("    } catch (error) {");
parts.push("      console.error('Failed to fetch products:', error);");
parts.push("    } finally {");
parts.push("      setLoading(false);");
parts.push("    }");
parts.push("  };");
parts.push("");
parts.push("  const fetchCategories = async () => {");
parts.push("    try {");
parts.push("      const response = await productsApi.getProducts({ limit: 100 });");
parts.push("      const products = response.data.data?.data || [];");
parts.push("      const cats = [...new Set(products.map((p: any) => p.category?.name).filter(Boolean))];");
parts.push("      setCategories(cats);");
parts.push("    } catch (error) {");
parts.push("      console.error('Failed to fetch categories:', error);");
parts.push("    }");
parts.push("  };");
parts.push("");
parts.push("  useEffect(() => {");
parts.push("    fetchProducts();");
parts.push("    fetchCategories();");
parts.push("  }, [page, limit, sort, order, category, search, minPrice, maxPrice]);");
parts.push("");
parts.push("  const updateParams = (newParams: Record<string, string | null>) => {");
parts.push("    const params = new URLSearchParams(searchParams.toString());");
parts.push("    Object.entries(newParams).forEach(([key, value]) => {");
parts.push("      if (value === null || value === '') {");
parts.push("        params.delete(key);");
parts.push("      } else {");
parts.push("        params.set(key, value);");
parts.push("      }");
parts.push("    });");
parts.push("    params.set('page', '1');");
parts.push("    router.push(`${pathname}?${params.toString()}`);");
parts.push("  };");
parts.push("");
parts.push("  const handleSortChange = (value: string) => {");
parts.push("    const [field, dir] = value.startsWith('-') ? [value.slice(1), 'DESC'] : [value, 'ASC'];");
parts.push("    updateParams({ sort: field, order: dir });");
parts.push("  };");
parts.push("");
parts.push("  const handleLimitChange = (value: string) => {");
parts.push("    updateParams({ limit: value });");
parts.push("  };");
parts.push("");
parts.push("  const handleCategoryChange = (value: string) => {");
parts.push("    updateParams({ category: value || null });");
parts.push("  };");
parts.push("");
parts.push("  const handleSearch = (e: React.FormEvent) => {");
parts.push("    e.preventDefault();");
parts.push("    const formData = new FormData(e.currentTarget as HTMLFormElement);");
parts.push("    const searchValue = formData.get('search') as string;");
parts.push("    updateParams({ search: searchValue || null });");
parts.push("  };");
parts.push("");
parts.push("  const handlePriceFilter = () => {");
parts.push("    updateParams({ minPrice: minPrice || null, maxPrice: maxPrice || null });");
parts.push("  };");
parts.push("");
parts.push("  const clearFilters = () => {");
parts.push("    updateParams({ category: null, search: null, minPrice: null, maxPrice: null });");
parts.push("  };");
parts.push("");
parts.push("  const hasActiveFilters = category || search || minPrice || maxPrice;");
parts.push("");
