flyway.url=jdbc:postgresql://postgres:5432/westos_dev  
flyway.user=westos  
flyway.password=westos_dev_password  
flyway.locations=filesystem:/flyway/sql  
flyway.baselineOnMigrate=true  
flyway.validateOnMigrate=true  
flyway.cleanDisabled=false  
flyway.outOfOrder=false  
flyway.table=flyway_schema_history  
flyway.placeholderReplacement=true  
flyway.placeholderPrefix=$\{  
flyway.placeholderSuffix=\} 
