apiVersion: v1
kind: ConfigMap
metadata:
  name: westos-frontend-config
  namespace: westos
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://api.westos.com"
  NEXT_PUBLIC_APP_URL: "https://www.westos.com"
  NEXT_PUBLIC_CDN_URL: "https://cdn.westos.com"